using System;
using System.Collections;
using System.Collections.Generic;
using MayorOfMedieval.Building;
using MayorOfMedieval.Economy;
using UnityEngine;

namespace MayorOfMedieval.Core
{
    /// <summary>
    /// Persists the village between sessions. Everything is keyed off BuildingKind rather
    /// than object names, so the save survives the world being regenerated by the editor
    /// tool. Restore order matters: buildings first, then their crews and piles.
    /// </summary>
    public class SaveManager : MonoBehaviour
    {
        private const string Key = "MayorOfMedieval.Save.v1";

        [Tooltip("Seconds between background auto-saves.")]
        [SerializeField] private float autoSaveInterval = 10f;

        public static SaveManager Instance { get; private set; }

        [Serializable] private class PileEntry { public int owner; public string pile; public int amount; }
        [Serializable] private class StationEntry { public int owner; public int workers; }
        [Serializable] private class TillEntry { public int owner; public int gold; }

        [Serializable]
        private class SaveData
        {
            public int gold;
            public int peakGold;
            public List<int> built = new List<int>();
            public List<StationEntry> stations = new List<StationEntry>();
            public List<PileEntry> piles = new List<PileEntry>();
            public List<TillEntry> tills = new List<TillEntry>();
            public int soldiers;
            public float px, py, pz;
            public bool hasPlayerPos;
        }

        private float timer;
        private bool restored;

        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.SubsystemRegistration)]
        private static void ResetStatics() => Instance = null;

        private void Awake()
        {
            if (Instance != null && Instance != this) { Destroy(this); return; }
            Instance = this;
        }

        // Buildings register their pads during their own Start, so restoring waits a frame.
        private IEnumerator Start()
        {
            yield return null;
            Load();
            restored = true;
        }

        private void Update()
        {
            if (!restored) return;

            timer += Time.deltaTime;
            if (timer < autoSaveInterval) return;
            timer = 0f;
            Save();
        }

        private void OnApplicationQuit() { if (restored) Save(); }

        private void OnApplicationPause(bool paused) { if (paused && restored) Save(); }

        public static void DeleteSave()
        {
            PlayerPrefs.DeleteKey(Key);
            PlayerPrefs.Save();
        }

        public bool HasSave => PlayerPrefs.HasKey(Key);

        // ------------------------------------------------------------------- save

        public void Save()
        {
            SaveData data = new SaveData();

            ResourceManager wallet = ResourceManager.Instance;
            if (wallet != null)
            {
                data.gold = wallet.Gold;
                data.peakGold = wallet.PeakGold;
            }

            BuildPad[] pads = FindObjectsByType<BuildPad>(FindObjectsInactive.Include, FindObjectsSortMode.None);
            foreach (BuildPad pad in pads)
            {
                if (!pad.IsBuilt) continue;
                data.built.Add((int)pad.Kind);

                GameObject building = pad.SpawnedBuilding;
                if (building == null) continue;

                WorkerStation station = building.GetComponent<WorkerStation>();
                if (station != null)
                    data.stations.Add(new StationEntry { owner = (int)pad.Kind, workers = station.WorkerCount });

                foreach (Stockpile pile in building.GetComponentsInChildren<Stockpile>(true))
                    data.piles.Add(new PileEntry { owner = (int)pad.Kind, pile = pile.gameObject.name, amount = pile.Amount });

                SalesPoint shop = building.GetComponent<SalesPoint>();
                if (shop != null)
                    data.tills.Add(new TillEntry { owner = (int)pad.Kind, gold = shop.PendingGold });

                Barracks barracks = building.GetComponent<Barracks>();
                if (barracks != null) data.soldiers = barracks.SoldierCount;
            }

            Transform player = PlayerRef.Root;
            if (player != null)
            {
                data.hasPlayerPos = true;
                data.px = player.position.x;
                data.py = player.position.y;
                data.pz = player.position.z;
            }

            PlayerPrefs.SetString(Key, JsonUtility.ToJson(data));
            PlayerPrefs.Save();
        }

        // ------------------------------------------------------------------- load

        public void Load()
        {
            if (!PlayerPrefs.HasKey(Key)) return;

            SaveData data = JsonUtility.FromJson<SaveData>(PlayerPrefs.GetString(Key));
            if (data == null) return;

            // 1. Wallet first, so the progression ladder reveals the right pads.
            ResourceManager wallet = ResourceManager.Instance;
            if (wallet != null) wallet.RestoreGold(data.gold, data.peakGold);

            // 2. Rebuild every completed building.
            Dictionary<BuildingKind, BuildPad> byKind = new Dictionary<BuildingKind, BuildPad>();
            foreach (BuildPad pad in FindObjectsByType<BuildPad>(FindObjectsInactive.Include, FindObjectsSortMode.None))
                byKind[pad.Kind] = pad;

            foreach (int kindId in data.built)
            {
                BuildPad pad;
                if (byKind.TryGetValue((BuildingKind)kindId, out pad)) pad.RestoreBuilt();
            }

            // 3. Now the buildings exist, put their contents back.
            foreach (StationEntry s in data.stations)
            {
                GameObject b = BuildingOf(byKind, s.owner);
                if (b == null) continue;
                WorkerStation station = b.GetComponent<WorkerStation>();
                if (station != null) station.RestoreWorkers(s.workers);
            }

            foreach (PileEntry p in data.piles)
            {
                GameObject b = BuildingOf(byKind, p.owner);
                if (b == null) continue;
                foreach (Stockpile pile in b.GetComponentsInChildren<Stockpile>(true))
                {
                    if (pile.gameObject.name != p.pile) continue;
                    pile.SetAmount(p.amount);
                    break;
                }
            }

            foreach (TillEntry t in data.tills)
            {
                GameObject b = BuildingOf(byKind, t.owner);
                if (b == null) continue;
                SalesPoint shop = b.GetComponent<SalesPoint>();
                if (shop != null) shop.SetPendingGold(t.gold);
            }

            if (data.soldiers > 0)
            {
                foreach (Barracks barracks in FindObjectsByType<Barracks>(FindObjectsInactive.Include, FindObjectsSortMode.None))
                    barracks.RestoreSoldiers(data.soldiers);
            }

            // 4. Put the Lord back where they stood.
            if (data.hasPlayerPos)
            {
                Transform player = PlayerRef.Root;
                if (player != null)
                {
                    CharacterController cc = player.GetComponent<CharacterController>();
                    if (cc != null) cc.enabled = false;
                    player.position = new Vector3(data.px, data.py, data.pz);
                    if (cc != null) cc.enabled = true;
                }
            }
        }

        private static GameObject BuildingOf(Dictionary<BuildingKind, BuildPad> byKind, int kindId)
        {
            BuildPad pad;
            return byKind.TryGetValue((BuildingKind)kindId, out pad) && pad != null ? pad.SpawnedBuilding : null;
        }
    }
}
